Fix building issue with libndctl
This patch fix following compilation error
src/common.inc:323: *** libndctl(version >= 60.1) is missing

Signed-off-by: Jakub Radtke <jakub.radtke@intel.com>